Revert the original files.

diff --git a/base/third_party/go-wrapper/go-wrapper b/base/third_party/go-wrapper/go-wrapper
--- a/base/third_party/go-wrapper/go-wrapper
+++ b/base/third_party/go-wrapper/go-wrapper
@@ -86,21 +86,25 @@ case "$cmd" in
 		;;
 		
 	run)
-		if [ -n "${GAE_SERVICE}" ]; then
-			service="${GAE_SERVICE}"
+		if [ -f "./source-context.json" ]; then
+			service="${GAE_SERVICE:-default}"
+			version="${GAE_VERSION:-default}"
+			goBinLoc="$(which $goBin)"
+			set +e; set -x; go-cloud-debug \
+				-sourcecontext ./source-context.json \
+				-appmodule "${service}" \
+				-appversion "${version}" \
+				-- "$goBinLoc" "$@"
+			exitCode="$?"
+			if [ "$exitCode" -eq 103 ]; then
+				# Fallback to running the binary itself if failed to get the application default credentials.
+				exec "$goBin" "$@"
+            else
+                exit "$exitCode"
+			fi
 		else
-			service="default"
+			set -x; exec "$goBin" "$@"
 		fi
-		if [ -n "${GAE_VERSION}" ]; then
-			version="${GAE_VERSION}"
-		else
-			version="default"
-		fi
-		set -x; exec go-cloud-debug \
-			-sourcecontext ./source-context.json \
-			-appmodule "${service}" \
-			-appversion "${version}" \
-            -- "$(which $goBin)" "$@"
 		;;
 		
 	*)
