Fix tab/space mismatch

diff --git a/base/third_party/go-wrapper/go-wrapper b/base/third_party/go-wrapper/go-wrapper
--- a/base/third_party/go-wrapper/go-wrapper
+++ b/base/third_party/go-wrapper/go-wrapper
@@ -1,5 +1,5 @@
 #!/bin/sh
-# set -e
+set -e
 
 usage() {
 	base="$(basename "$0")"
@@ -97,7 +97,7 @@ case "$cmd" in
 				-- "$goBinLoc" "$@"
 			exitCode="$?"
 			if [ "$exitCode" -eq 103 ]; then
-                # Fallback to running the binary itself if failed to get the application default credentials.
+				# Fallback to running the binary itself if failed to get the application default credentials.
 				exec "$goBin" "$@"
             else
                 exit "$exitCode"
