Fallback only with exit code 103. Exit with any other exit code.

diff --git a/base/third_party/go-wrapper/go-wrapper b/base/third_party/go-wrapper/go-wrapper
--- a/base/third_party/go-wrapper/go-wrapper
+++ b/base/third_party/go-wrapper/go-wrapper
@@ -1,5 +1,5 @@
 #!/bin/sh
-set -e
+# set -e
 
 usage() {
 	base="$(basename "$0")"
@@ -89,14 +89,18 @@ case "$cmd" in
 		if [ -f "./source-context.json" ]; then
 			service="${GAE_SERVICE:-default}"
 			version="${GAE_VERSION:-default}"
-			goBinLoc="$(which goBin)"
+			goBinLoc="$(which $goBin)"
 			set +e; set -x; go-cloud-debug \
 				-sourcecontext ./source-context.json \
 				-appmodule "${service}" \
 				-appversion "${version}" \
 				-- "$goBinLoc" "$@"
-			if [ "$?" -eq 103 ]; then # fallback to running the binary itself if failed to get the application default credentials.
-				set -x; exec "$goBin" "$@"
+			exitCode="$?"
+			if [ "$exitCode" -eq 103 ]; then
+                # Fallback to running the binary itself if failed to get the application default credentials.
+				exec "$goBin" "$@"
+            else
+                exit "$exitCode"
 			fi
 		else
 			set -x; exec "$goBin" "$@"
