Change code to 103

diff --git a/base/third_party/go-wrapper/go-wrapper b/base/third_party/go-wrapper/go-wrapper
--- a/base/third_party/go-wrapper/go-wrapper
+++ b/base/third_party/go-wrapper/go-wrapper
@@ -89,12 +89,13 @@ case "$cmd" in
 		if [ -f "./source-context.json" ]; then
 			service="${GAE_SERVICE:-default}"
 			version="${GAE_VERSION:-default}"
+			goBinLoc="$(which goBin)"
 			set +e; set -x; go-cloud-debug \
 				-sourcecontext ./source-context.json \
 				-appmodule "${service}" \
 				-appversion "${version}" \
-				-- "$(which $goBin)" "$@"
-			if [ "$?" -eq 3 ]; then # fallback to running the binary itself if failed to get the application default credentials.
+				-- "$goBinLoc" "$@"
+			if [ "$?" -eq 103 ]; then # fallback to running the binary itself if failed to get the application default credentials.
 				set -x; exec "$goBin" "$@"
 			fi
 		else
